language: objective-c
osx_image: xcode8
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods -v 1.1.1
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/MKUnits.xcworkspace -scheme MKUnits-Example -sdk iphonesimulator -destination 'name=iPhone 6,OS=10.0' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
